[package]
name = "prog_puzz"
version = "1.7.0"
edition = "2024"

[dependencies]
macroquad = "=0.4.14"
tile_engine = {package = "programming_engine", path = "../programming_engine" }
log = "0.4.28"
env_logger = "0.11.8"
