[package]
name = "prog_puzz"
version = "1.6.1"
edition = "2024"

[dependencies]
macroquad = "=0.4.14"
tile_engine = {package = "programming_engine", path = "../programming_engine" }
log = "0.4.28"
env_logger = "0.11.8"
quad-storage = "0.1.0"
quad-timestamp = "0.1.2"
