[package]
name = "tile_engine"
version = "1.0.2"
edition = "2024"

[dependencies]
macroquad = "=0.4.7"
futures = "0.3.30"
derive_more = "0.99"
assrt = {git = "https://github.com/CartesianDaemon/assrt.git", branch = "v0.2"}
culpa = "1.0.2"
log = "0.4.28"
env_logger = "0.11.8"
